x-veld:
  code:
    description:
    topic:
    additional:

    input:
      - volume: /veld/input/
        file_type:
        content:
        environemnt_var:

    output:
      - volume: /veld/output/
        file_type:
        content:
        environemnt_var:

    config:
      - environemnt_var:
        description:
        var_type:
        default:
        optional:

services:
  veld_wordembeddings_germanet_evaluation:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./src/:/veld/code/
    environment:
      POSTGRES_USER: null
      POSTGRES_PASSWORD: null
      POSTGRES_DB: null
      POSTGRES_HOST: null
      POSTGRES_PORT: null
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge

